# Generated by Django 4.0.3 on 2023-05-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_answer_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='auther',
            new_name='author',
        ),
    ]
